name: CI

on:
  push:
    branches:
      - main
      - publish-to-maven-central
  pull_request:

jobs:
  assemble:
    runs-on: ubuntu-24.04
    environment: dev
    env:
      ARTIFACTORY_REPO: besu-maven
      ARTIFACTORY_ORG: hyperledger
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}
            ${{ runner.os }}-gradle-

      - name: Assemble
        run: |
          env
          ./gradlew --no-daemon clean compileJava compileTestJava assemble

      - name: Upload workspace
        uses: actions/upload-artifact@v4
        with:
          name: workspace
          path: |
            ./
            !./.git/**
          retention-days: 5

  unitTests:
    needs: assemble
    runs-on: ubuntu-24.04
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'adopt'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/versions.gradle') }}
            ${{ runner.os }}-gradle-

      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Build
        run: ./gradlew --no-daemon build

      - name: Store distribution artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jar
          path: 'build/libs/'

  publishToMavenCentral:
    needs: 
      - assemble
      - unitTests
    runs-on: ubuntu-24.04
    environment: publish
    permissions:
      contents: write
      id-token: write
      packages: write    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java and Gradle
        id: setup-java-gradle
        uses: ConsenSys/github-actions/java-setup-gradle@main
        with:
          DISTRIBUTION: 'adopt'

      - name: Download workspace
        uses: actions/download-artifact@v4
        with:
          name: workspace

      - name: Determine version
        id: project_version
        uses: ConsenSys/github-actions/java-get-project-version@main

      - name: Publish to maven central
        if: "!startsWith(github.ref, 'refs/tags/')"
        env:
          GRADLE_OPTS: "-Xmx4g -Xms512m"
          JAVA_OPTS: "-Xmx4g"
          JRELEASER_OPTS: "-Xmx4g"
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GITHUB_USERNAME: ${{ github.actor }}
          JRELEASER_GITHUB_EMAIL: ${{ github.actor }}@users.noreply.github.com
          JRELEASER_GPG_PASSPHRASE : ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY : ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY : ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME : ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD : ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
          JRELEASER_NEXUS2_USERNAME : ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_NEXUS2_PASSWORD : ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}    
        run: ./gradlew clean build assemble publish jreleaserFullRelease -PreleaseVersion=${{ steps.project_version.outputs.specific-version }} --no-daemon --stacktrace --info