name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-24.04
    environment: publish
    permissions:
      contents: write
      id-token: write
    env:
      GRADLE_OPTS: -Xmx2g -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java and Gradle
        id: setup-java-gradle
        uses: ConsenSys/github-actions/java-setup-gradle@main
        with:
          DISTRIBUTION: 'adopt'

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Build with Gradle
        run: ./gradlew build -PreleaseVersion=${{ steps.get_version.outputs.VERSION }}

      - name: Test with Gradle
        run: ./gradlew test

      - name: Create release notes
        run: |
          echo "## Release ${{ github.ref_name }}" > output.md
          echo "./build/libs/besu-fleet-plugin-${{ steps.get_version.outputs.VERSION }}.jar" >> output.md
          echo "SHA256: $(sha256sum ./build/libs/besu-fleet-plugin-${{ steps.get_version.outputs.VERSION }}.jar | awk '{ print $1 }' )" >> output.md
          echo "" >> output.md

      - name: Upload Release Asset
        id: release_publish
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: Release ${{ github.ref_name }}
          body_path: output.md
          generate_release_notes: true
          fail_on_unmatched_files: true          
          files: ./build/libs/besu-fleet-plugin-${{ steps.get_version.outputs.VERSION }}.jar

      - name: Publish to maven central
        if: "!startsWith(github.ref, 'refs/tags/')"
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JRELEASER_GITHUB_USERNAME: ${{ github.actor }}
          JRELEASER_GITHUB_EMAIL: ${{ github.actor }}@users.noreply.github.com
          JRELEASER_GPG_PASSPHRASE : ${{ secrets.JRELEASER_GPG_PASSPHRASE }}
          JRELEASER_GPG_SECRET_KEY : ${{ secrets.JRELEASER_GPG_SECRET_KEY }}
          JRELEASER_GPG_PUBLIC_KEY : ${{ secrets.JRELEASER_GPG_PUBLIC_KEY }}
          JRELEASER_MAVENCENTRAL_USERNAME : ${{ secrets.JRELEASER_MAVENCENTRAL_USERNAME }}
          JRELEASER_MAVENCENTRAL_PASSWORD : ${{ secrets.JRELEASER_MAVENCENTRAL_PASSWORD }}
        run: ./gradlew publish jreleaserFullRelease -PreleaseVersion=${{ steps.get_version.outputs.VERSION }}

